# TaskFlow
Application de gestion de tâches collaborative

image::https://classroom.github.com/assets/open-in-vscode-2e0aaae1b6195c2367325f4f02e2d04e9abb55f0b24a779b69b11b9e10269abc.svg["Open in Visual Studio Code", link="https://classroom.github.com/online_ide?assignment_repo_id=16928608&assignment_repo_type=AssignmentRepo"]

:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:


// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-2024-2025-g2b12 // à changer !


//---------------------------------------------------------------

toc::[]

== *Équipe et Rôles*

Le projet est réalisé par :

|===
2+^| *Équipe G2b12*
2+|
| Nom | Rôle |
https://github.com/34lks66[*Mucahit Lekesiz*] | *Pire Chef d'équipe du monde et de loins le meilleur dans sa catégorie* |
https://github.com/Ezeloss[*Léo Guinvarc'h*] | *Développeur* |
https://github.com/Laloix23[*Loic Phrakousonh*] | *Développeur* |
|===


== *Contexte général*

Le projet est à réaliser dans le cadre d'une préparation par rapport à la rentrée à venir. Il a pour objectif de concevoir, développer et valider une petite application web qui permet à un groupde d'utilisateurs : 

* Créer des tâches

* Les assigner à un membre

* Suivre leur avancement (À faire / En cours / Terminé)

* Ajouter des commentaires ou des deadlines

L’application sera simple, mais elle doit respecter les bonnes pratiques de conception et de développement vues en BUT.

== *Objectifs pédagogiques*

Le projet doit permettre de réviser les grandes compétences attendues en 3ème année BUT Informatique (parcours A) : 

*Conception*

- Rédiger un cahier des charges / backlog agile. 

- Réaliser une maquette de l’interface.

*Développement*

- Développer l'application avec React.

- Intégrer une API REST pour la gestion des données.

*Validation/ Qualité*

- Écrire des tests unitaires.

*Organisation de projet*

- Travailler en mode agile.

- Utiliser GitHub.

- Répartir les rôles (chef de projet, dev backend, dev frontend...).


== *Technologies Utilisées*

- **Frontend**: React

- **Backend**: 

- **Base de données**:

- **Outils**: Git, GitHub, Visual Studio Code

== *Réalisations*

=== Livrables

Vous trouverez ci-dessous les travaux et livrables réalisés par l'équipe classées au fur et à mesure de l'avancée du projet :

|===
3+^| *LIVRABLES*
3+|
| *SEMAINE* | *SOLUTION* |*LIEN*

|===

=== Documentations

Cette section regroupe les principales documentations du projet (de la conception, au développement jusqu'à l’utilisation de l’application). 

|===
|DOCUMENTATION
| [Document de conception]
| [Document Utilisateur]
| [Document Technique]
| [Cahier de Recette]
| [Rapport de Projet]
|===
